#!/bin/bash

# Copyright 2012 Alexander Lochmann
#
# This file is part of SystemTap4Android.
#
# SystemTap4Android is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SystemTap4Android is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with SystemTap4Android.  If not, see <http://www.gnu.org/licenses/>.


CONF_DIR="config"
CONF_EXT=".conf"
MODULE_DIR="modules"
SCRIPT_DIR="scripts"

PREFIX=`pwd`"/installed/"
STAP=$PREFIX"/bin/stap"
TAPSETS=$PREFIX"/share/systemtap/tapset/"
STAP_RUNTIME=$PREFIX"/share/systemtap/runtime/"

ARCHITECTURES=("x86" "arm" "arm64")
COMPILER_PREFIX_LIST_ARM64=("/home/xhyang/src/pulpfiction/prebuilts/gcc/linux-x86/aarch64/linaro-aarch64_linux-2014.09/bin/aarch64-linux-gnu-")
COMPILER_PREFIX_LIST_ARM=("arm-none-linux-gnueabi-")
COMPILER_PREFIX_LIST_X86=("" "i686-linux-android-")

export SYSTEMTAP_TAPSET=${TAPSETS}
PROBE_FUNC=" "

function listSupportedDevices()
{
	echo -n "devices: "
	ls ${CONF_DIR}/*${CONF_EXT} >/dev/null 2>&1
	if [ $? -gt 0 ];
	then
		echo "no devices found"
		return
	fi
	for device in `ls ${CONF_DIR}/*${CONF_EXT}`;
	do
		device=`basename ${device}`
		echo -n ${device%${CONF_EXT}}","
	done;
	echo "."
}

function checkCompiler()
{
	eval COMPILER_PREFIX_LIST=( \"\${COMPILER_PREFIX_LIST_`echo ${KERNEL_ARCH}| tr '[:lower:]' '[:upper:]'`[@]}\")

	for cur_compiler_prefix in "${COMPILER_PREFIX_LIST[@]}"
	do
		CUR_GCC="${cur_compiler_prefix}gcc"
		RET=`${CUR_GCC} --version 2>&1`
		if [ $? -eq 0 ];
		then
			#COMPILER_PREFIX=`dirname \`which ${CUR_GCC}\``"/${cur_compiler_prefix}"
			COMPILER_PREFIX=${cur_compiler_prefix}
			return
		fi
	done;

	echo "No suitable compiler found. Check your PATH" >&2
	exit 1
}

function getKernelInfos()
{
	if [ ! -d ${CONF_DIR} ];
	then
		echo "conf directory does not exist" >&2
		exit 1
	fi
	DEVICE=$1
	CONF_FILE=${CONF_DIR}/${DEVICE}${CONF_EXT}

	if [ -f ${CONF_FILE} ];
	then
		#KERNEL_SRC=`cat ${CONF_FILE}`
		. ${CONF_FILE}

		ARCH_FOUND=0
		for arch in ${ARCHITECTURES[@]}
		do
			if [ ${arch} = ${KERNEL_ARCH} ];
			then
				ARCH_FOUND=1
			fi
		done
		if [ ${ARCH_FOUND} -eq 0 ];
		then
			echo "unknown kernel architecture '${KERNEL_ARCH}'. Check the corresponding file: ${CONF_FILE}" >&2
			exit 1
		fi

		if [ ! -d ${KERNEL_SRC} ];
		then
			echo "kernel source tree (${KERNEL_SRC}) does not exit. Check the corresponding config file: ${CONF_FILE}" >&2
			exit 1
		fi
	else
		echo "config file (${CONF_FILE}) does not exist." >&2
		exit 1
	fi
}

function usage()
{
	echo "usage: build-module <skriptname> <device> [stap arguments (forwardded to the stap compiler)]]"
	listSupportedDevices
	exit 1
}

if [ $# -lt 2 ];
then
       usage $0
fi

while getopts "f:s:d:" arg #选项后面的冒号表示该选项需要参数
do
    case $arg in
        s)
            SCRIPT=$OPTARG
            ;;
        d)
            getKernelInfos $OPTARG
            ;;
        f)
            PROBE_FUNC=$OPTARG
            ;;
        ?)  #当有不认识的选项的时候arg为?
        echo "unkonw argument"
        exit 1
        ;;
    esac
done

checkCompiler

if [ ! -f ${SCRIPT_DIR}/${SCRIPT}".stp" ];
then
	echo "The specifid script (${SCRIPT}.stp) does not exist" >&2
	exit 1
fi

MODULE_NAME=${SCRIPT//./}


if [ ! -d ${MODULE_DIR} ]; then
	echo "module directory does not exist. Creating it..."
	mkdir ${MODULE_DIR}
fi

if [ ! -d ${MODULE_DIR}"/"${DEVICE} ]; then
	mkdir ${MODULE_DIR}"/"${DEVICE}
fi

if [ -z ${COMPILER_PREFIX} ];
then
	CROSS_COMPILE=""
else
	CROSS_COMPILE="-B CROSS_COMPILE=${COMPILER_PREFIX}"
fi

STAP_CMD="${STAP} -p 4 -v -a ${KERNEL_ARCH} ${CROSS_COMPILE} -r ${KERNEL_SRC} -R ${STAP_RUNTIME} -t -k -g -m ${MODULE_NAME} ${SCRIPT_DIR}/${SCRIPT}.stp ${PROBE_FUNC}"
echo "Executing: ${STAP_CMD}"
${STAP_CMD}

if [ -f ${MODULE_NAME}".ko" ]; then
	mv ${MODULE_NAME}".ko" ${MODULE_DIR}"/"${DEVICE}"/"${MODULE_NAME}".ko"
fi;
